name: ğŸ” Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    types:
      - opened
    branches:
      - 'dev_*'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Setup Node
        uses: actions/checkout@v5

      - name: ğŸ§ª Unit Tests
        run: pnpm test
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Setup Node
        uses: actions/checkout@v5

      - name: ğŸ“¦ Install Vercel CLI and pnpm
        run: npm install --global vercel@latest pnpm

      - name: ğŸ”½ Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸ”¨ Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
